/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;
import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Tehtavalista lista = new Tehtavalista();
        Scanner lukija = new Scanner(System.in);

        Kayttoliittyma liittyma = new Kayttoliittyma(lista, lukija);

        lista.lisaa("lue kurssimateriaalia");
        lista.lisaa("katso uusin fool us");
        lista.lisaa("ota rennosti");
        lista.tulosta();
        lista.poista(2);
        lista.tulosta();
        lista.lisaa("osta rusinoita");
        lista.tulosta();

        liittyma.kaynnista();
    }
}

